# Generated by Django 4.2.6 on 2023-10-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=30)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='blog.comment')),
            ],
        ),
    ]
